# -*- mode: ruby -*-
# vi: set ft=ruby :

$master_script = <<SCRIPT
set -ex
date > /etc/vagrant_box_build_time

cat << HOST >> /etc/hosts
10.0.10.10  server1.example.com server1  
10.0.10.11  server2.example.com server2
HOST

echo "nameserver 8.8.8.8" > /etc/resolv.conf
sed -i s/SELINUX=enforcing/SELINUX=disabled/g /etc/selinux/config
setenforce 0
echo "vagrant ALL=(root) NOPASSWD:ALL" >> /etc/sudoers.d/vagrant
chmod 0440 /etc/sudoers.d/vagrant

sed -i.orgi "s/PasswordAuthentication no/PasswordAuthentication yes/g"    /etc/ssh/sshd_config
systemctl restart sshd
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.define :server1 do |node|
      node.vm.hostname = "server1.example.com"
      node.vm.provider :libvirt do |libvirt|
        libvirt.uri = 'qemu+unix:///system'  
        libvirt.cpus = 1
        libvirt.memory = 1024
        libvirt.nested = true
        libvirt.storage :file, :size => '2G'
      end
      #eth1 network
      node.vm.network :private_network, ip: "10.0.10.10"
      node.vm.provision :shell, :inline => $master_script
  end
  config.vm.define :server2 do |node|
      node.vm.hostname = "server2.example.com"
      node.vm.provider :libvirt do |libvirt|
        libvirt.uri = 'qemu+unix:///system'  
        libvirt.cpus = 1
        libvirt.memory = 1024
        libvirt.nested = true
        libvirt.storage :file, :size => '2G'
      end
      #eth1 network
      node.vm.network :private_network, ip: "10.0.10.11"
      node.vm.provision :shell, :inline => $master_script
  end
end
